version: '3.8'

services:
  n1-rabbitmq:
    image: rabbitmq:3-management
    container_name: n1-rabbitmq-broker
    # Đã ẩn ports để tránh xung đột với nhóm khác
    networks:
      - n1-project-network

  n1-postgres:
    image: postgres:15-alpine
    container_name: n1-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 03092005Ah
      POSTGRES_DB: ProjectDB
    volumes:
      - n1-postgres-data:/var/lib/postgresql/data
    networks:
      - n1-project-network

  n1-project-member-service:
    build:
      context: ./ProjectMemberService
      dockerfile: Dockerfile
    container_name: n1-project-member-service
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Jwt__Key=SuperSecretKey_ProjectMemberService_2024_DoNotShare!
      - Jwt__Issuer=ProjectMemberService
      - Jwt__Audience=ProjectMemberServiceClient
      - ConnectionStrings__DefaultConnection=Host=n1-postgres;Database=ProjectDB;Username=postgres;Password=03092005Ah;Port=5432
      - RabbitMq__Host=n1-rabbitmq
      - RESET_DB=true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - n1-rabbitmq
      - n1-postgres
    restart: unless-stopped
    networks:
      - n1-project-network

networks:
  n1-project-network:
    driver: bridge

volumes:
  n1-postgres-data:
